(eval-when-compile
  (require 'color-theme))

(defun color-theme-choco ()
  "Choco theme. Converted from the textMate theme by imtayadeway."
  (interactive)
  (color-theme-install
   '(color-theme-choco
    ((background-color . "#180C0C")
     (foreground-color . "#C3BE98")
     (cursor-color . "#A7A7A7")
    (trailing-whitespace ((t (:background "#524949"))))
    (whitespace-trailing ((t (:background "#524949"))))

    (border ((t (:background "#361f1a" ))))
    (css-property ((t (:foreground "#af977b" ))))
    (css-proprietary-property ((t (:foreground "#af977b" ))))
    (css-selector ((t (:foreground "#7690a4" ))))
    (cursor ((t (:background "#a7a7a7" ))))
    (default ((t (:foreground "#c3be98" :background "#180c0c" ))))
    (diff-added ((t (:foreground "#f8f8f8" :background "#253b22" ))))
    (diff-changed ((t (:foreground "#f8f8f8" :background "#4a410d" ))))
    (diff-header ((t (:foreground "#f8f8f8" :italic t :background "#0e2231" ))))
    (diff-hunk-header ((t (:foreground "#f8f8f8" :italic t :background "#0e2231" ))))
    (diff-removed ((t (:foreground "#f8f8f8" :background "#420e09" ))))
    (font-lock-builtin-face ((t (:foreground "#c29863" ))))
    (font-lock-comment-delimiter-face ((t (:foreground "#679d47" :background "#180c0c" ))))
    (font-lock-comment-face ((t (:foreground "#679d47" :background "#180c0c" ))))
    (font-lock-constant-face ((t (:foreground "#d77261" ))))
    (font-lock-doc-face ((t (:foreground "#ddf2a4" ))))
    (font-lock-function-name-face ((t (:foreground "#c29863" ))))
    (font-lock-keyword-face ((t (:foreground "#b3935c" ))))
    (font-lock-negation-char-face ((t (:foreground "#b3935c" ))))
    (font-lock-preprocessor-face ((t (:foreground "#8996a8" ))))
    (font-lock-regexp-grouping-backslash ((t (:foreground "#cf7d34" ))))
    (font-lock-regexp-grouping-construct ((t (:foreground "#cf7d34" ))))
    (font-lock-string-face ((t (:foreground "#ddf2a4" ))))
    (font-lock-type-face ((t (:foreground "#f1e694" ))))
    (font-lock-variable-name-face ((t (:foreground "#7989a6" ))))
    (font-lock-warning-face ((t (:foreground "#f8f8f8" :background "#462543" ))))
    (fringe ((t (:background "#361f1a" ))))
    (highlight ((t (:background "#636368" ))))
    (hl-line ((t (:background "#361f1a" ))))
    (isearch ((t (:foreground "#f8f8f8" :background "#4a410d" ))))
    (isearch-fail ((t (:foreground "#f8f8f8" :background "#420e09" ))))
    (iswitchb-current-match ((t (:foreground "#f8f8f8" :background "#253b22" ))))
    (iswitchb-invalid-regexp ((t (:foreground "#f8f8f8" :background "#420e09" ))))
    (iswitchb-single-match ((t (:foreground "#f8f8f8" :background "#253b22" ))))
    (iswitchb-virtual-matches ((t (:foreground "#f8f8f8" :background "#4a410d" ))))
    (linum ((t (:background "#361f1a" ))))
    (match ((t (:foreground "#f8f8f8" :background "#253b22" ))))
    (menu ((t (:foreground "#c3be98" :background "#180c0c" ))))
    (minibuffer-prompt ((t (:foreground "#9f785b" ))))
    (mode-line ((t (:foreground "#f8f8f8" :italic t :background "#0e2231" ))))
    (mode-line-buffer-id ((t (:foreground "#6d4c2f" ))))
    (mode-line-emphasis ((t (:bold t ))))
    (mode-line-highlight ((t (:italic t ))))
    (mode-line-inactive ((t (:background "#636368" ))))
    (org-agenda-dimmed-todo-face ((t (:foreground "#679d47" :background "#180c0c" ))))
    (org-column ((t (:background "#361f1a" ))))
    (org-column-title ((t (:background "#361f1a" ))))
    (org-done ((t (:foreground "#f8f8f8" :background "#253b22" ))))
    (org-hide ((t (:foreground "#180c0c" ))))
    (org-todo ((t (:foreground "#f8f8f8" :background "#462543" ))))
    (org-upcoming-deadline ((t (:foreground "#d2a8a1" :italic t :underline t ))))
    (org-warning ((t (:foreground "#f8f8f8" :background "#462543" ))))
    (region ((t (:background "#636368" ))))
    (secondary-selection ((t (:background "#636368" ))))
    (show-paren-match-face ((t (:background "#636368" ))))
    (show-paren-mismatch-face ((t (:foreground "#f8f8f8" :background "#462543" ))))
    ))))

(provide 'color-theme-choco)
