#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --show-toplevel`"
trap 'rm -f "$dir/$$.TAGS"' EXIT
git ls-files | \
    ctags -a -e -f "$dir/$$.TAGS" --tag-relative -R --exclude=.git,log,tmp --languages=-javascript,sql
mv "$dir/$$.TAGS" "$dir/TAGS"
